name: vqvae
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.5.1+cu121; sys_platform=="linux" and platform_machine != "aarch64"
    - torchvision==0.20.1+cu121; sys_platform=="linux" and platform_machine != "aarch64"
    - torch==2.5.1; sys_platform=="darwin" or platform_machine == "aarch64"
    - torchvision==0.20.1; sys_platform=="darwin" or platform_machine == "aarch64"
    - netron
    - matplotlib
    - tqdm
    - tensorboard
    - torchsummary
    - scipy
    - -e ../pyviewer

# conda env create -f environment.yml
# conda env update -f environment.yml